ifs/urls.py
from django.conf.urls import patterns, url
from .view import SignupCompletionView


urlpatterns = patterns(
    '',
    url(r'^signup-completion/?$', SignupCompletionView.as_view(), name='signup_completion'),
)

timtec/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.views.generic import TemplateView
from accounts.views import (ProfileEditView, ProfileView, UserSearchView,
                            TimtecUserViewSet, TimtecUserAdminViewSet, StudentSearchView,
                            AcceptTermsView)

from core.views import (CourseView, GenericCourseView, CourseViewSet,
                        CourseProfessorViewSet, EnrollCourseView, HomeView,
                        UserCoursesView, ContactView, LessonDetailView,
                        LessonViewSet, StudentProgressViewSet,
                        UserNotesViewSet, CoursesView, CourseThumbViewSet,
                        ProfessorMessageViewSet, CourseStudentViewSet,
                        CarouselCourseView, ClassListView,
                        ClassCreateView, ClassUpdateView, ClassDeleteView,
                        ClassRemoveUserView, ClassAddUsersView, ClassViewSet,
                        ClassEvaluationsView,
                        FlatpageViewSet, CoursePictureUploadViewSet,
                        ResumeCourseView, FlatpageView, CourseAuthorViewSet,
                        CourseCertificationViewSet,
                        CourseCertificationDetailView,
                        CertificationProcessViewSet,
                        EvaluationViewSet, CertificateTemplateViewSet,
                        CertificateTemplateImageViewSet, RequestCertificateView,
                        EmitReceiptView, ProfileViewSet)

from activities.views import AnswerViewSet
from forum.views import (CourseForumView, QuestionView, QuestionCreateView, QuestionViewSet,
                         QuestionVoteViewSet, AnswerVoteViewSet, AnswerViewSet as ForumAnswerViewSet)
from course_material.views import CourseMaterialView, FileUploadView, CourseMaterialViewSet, CourseMaterialFileViewSet
from notes.views import NotesViewSet, CourseNotesView, UserNotesView
from reports.views import UserCourseStats, CourseStatsByLessonViewSet, UserCourseLessonsStats
from rest_framework import routers
from django_markdown import flatpages

# Uncomment the next two lines to enable the admin:
from django.contrib import admin as django_admin
django_admin.autodiscover()

flatpages.register()

router = routers.DefaultRouter(trailing_slash=False)
router.register(r'user', TimtecUserViewSet)
router.register(r'profile', ProfileViewSet)
router.register(r'user_admin', TimtecUserAdminViewSet)
router.register(r'course', CourseViewSet)
router.register(r'course_carousel', CarouselCourseView)
router.register(r'course_professor', CourseProfessorViewSet)
router.register(r'course_professor_picture', CoursePictureUploadViewSet)
router.register(r'course_author', CourseAuthorViewSet)
router.register(r'course_student', CourseStudentViewSet)
router.register(r'professor_message', ProfessorMessageViewSet)
router.register(r'coursethumbs', CourseThumbViewSet)
router.register(r'lessons', LessonViewSet)
router.register(r'answer', AnswerViewSet)
router.register(r'student_progress', StudentProgressViewSet)
router.register(r'forum_question', QuestionViewSet)
router.register(r'forum_answer', ForumAnswerViewSet)
router.register(r'question_vote', QuestionVoteViewSet)
router.register(r'answer_vote', AnswerVoteViewSet)
router.register(r'course_material', CourseMaterialViewSet)
router.register(r'course_material_file', CourseMaterialFileViewSet)
router.register(r'note', NotesViewSet)
router.register(r'user_notes', UserNotesViewSet)
router.register(r'reports', UserCourseStats)
router.register(r'lessons_user_progress', UserCourseLessonsStats)
router.register(r'course_stats', CourseStatsByLessonViewSet)
router.register(r'course_classes', ClassViewSet)
router.register(r'flatpage', FlatpageViewSet)
router.register(r'course_certification', CourseCertificationViewSet)
router.register(r'certification_process', CertificationProcessViewSet)
router.register(r'evaluation', EvaluationViewSet)
router.register(r'certificate_template', CertificateTemplateViewSet)
router.register(r'certificate_template_images', CertificateTemplateImageViewSet)

urlpatterns = patterns(
    '',
    url(r'^$', HomeView.as_view(), name='home_view'),
    url(r'^courses', CoursesView.as_view(), name='courses'),

    # Uncomment the next line to enable the admin:
    url(r'^django/admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^django/admin/', include(django_admin.site.urls)),

    # Privileged browsing
    url(r'^admin/', include('administration.urls')),

    # Public browsing
    url(r'^my-courses/$', UserCoursesView.as_view(), name='user_courses'),

    url(r'^emit_recipt/(?P<course_id>[-a-zA-Z0-9_]+)$', EmitReceiptView.as_view(), name='emit_recipt'),
    url(r'^request_certificate/(?P<course_id>[-a-zA-Z0-9_]+)$',
        RequestCertificateView.as_view(),
        name='request_certificate'),

    url(r'^certificate/(?P<slug>[-a-zA-Z0-9_]+)/$', CourseCertificationDetailView.as_view(), name='certificate'),
    url(r'^certificate/(?P<slug>[-a-zA-Z0-9_]+)/print/$',
        CourseCertificationDetailView.as_view(template_name="certificate_print.html"),
        name='certificate-print'),
    url(r'^certificate/(?P<slug>[-a-zA-Z0-9_]+)/download/$', CourseCertificationDetailView.as_view(),
        name='certificate-download'),
    url(r'^accept_terms/$', AcceptTermsView.as_view(), name='accept_terms'),
    url(r'^course/(?P<slug>[-a-zA-Z0-9_]+)/intro/$', CourseView.as_view(), name='course_intro'),
    url(r'^course/(?P<slug>[-a-zA-Z0-9_]+)/enroll/$', EnrollCourseView.as_view(), name='enroll_course'),
    url(r'^course/(?P<slug>[-a-zA-Z0-9_]+)/resume/$', ResumeCourseView.as_view(), name='resume_course'),
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/lesson/(?P<slug>[-a-zA-Z0-9_]+)/$', LessonDetailView.as_view(), name='lesson'),
    url(r'^html5/', TemplateView.as_view(template_name="html5.html")),
    url(r'^empty/', TemplateView.as_view(template_name="empty.html")),
    url(r'^contact/?$', ContactView.as_view(), name="contact"),

    # Classes
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/classes/$', ClassListView.as_view(), name='classes'),
    url(r'^class/create/$', ClassCreateView.as_view(), name='class-create'),
    url(r'^class/(?P<pk>[0-9]+)/$', ClassUpdateView.as_view(), name='class'),
    url(r'^class/(?P<pk>[0-9]+)/delete/$', ClassDeleteView.as_view(), name='class-delete'),
    url(r'^class/(?P<pk>[0-9]+)/remove_user/$', ClassRemoveUserView.as_view(), name='class-remove-user'),
    url(r'^class/(?P<pk>[0-9]+)/add_users/$', ClassAddUsersView.as_view(), name='class-add-users'),
    url(r'^class/(?P<pk>[0-9]+)/evaluations/$', ClassEvaluationsView.as_view(), name='class-evaluations'),

    # Evaluations
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/course_evaluations/$', GenericCourseView.as_view(template_name="course-evaluations.html"), name='course-evaluations'),

    # Services
    url(r'^api/', include(router.urls)),
    # Forum
    url(r'^forum/(?P<course_slug>[-a-zA-Z0-9_]+)/$', CourseForumView.as_view(), name='forum'),
    url(r'^forum/question/(?P<slug>[-a-zA-Z0-9_]+)/$', QuestionView.as_view(), name='forum_question'),
    url(r'^forum/question/add/(?P<course_slug>[-a-zA-Z0-9_]+)/$', QuestionCreateView.as_view(), name='forum_question_create'),

    # Course Material
    url(r'^course/(?P<slug>[-a-zA-Z0-9_]+)/material/file_upload/$', FileUploadView.as_view(), name='file_upload'),
    url(r'^course/(?P<slug>[-a-zA-Z0-9_]+)/material/$', CourseMaterialView.as_view(), name='course_material'),

    # Notes
    url(r'^notes/(?P<username>[\w.+-]+)?$', UserNotesView.as_view(), name='user_notes'),
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/mynotes/$', CourseNotesView.as_view(), name='user_course_notes'),

    # Messages
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/messages/$', GenericCourseView.as_view(template_name="messages.html"), name='messages'),
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/message/(?P<message_id>[1-9][0-9]*)$', GenericCourseView.as_view(template_name="message.html"), name='message_detail'),

    # Reports
    url(r'^course/(?P<course_slug>[-a-zA-Z0-9_]+)/reports/$', GenericCourseView.as_view(template_name="administration/stats.html"), name='reports'),

    # Authentication
    url(r'^logout/', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='timtec_logout'),

    url(r'^profile/edit/?$', ProfileEditView.as_view(), name="profile_edit"),
    url(r'^profile/(?P<username>[\w.+-]+)?/?$', ProfileView.as_view(), name="profile"),

    # The django-allauth
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/user_search/?$', UserSearchView.as_view(), name='user_search'),
    url(r'^api/student_search/?$', StudentSearchView.as_view(), name='student_search'),

    url(r'^pages(?P<url>.*)$', FlatpageView.as_view(), name='flatpage'),

    # The django-rosetta
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^markdown/', include('django_markdown.urls')),

)

if settings.TWITTER_USER != '':
    from core.views import TwitterApi

    urlpatterns += (url(r'^api/twitter/?$', TwitterApi.as_view(), name='twitter'),)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'ifs' in settings.INSTALLED_APPS:
    urlpatterns += (url(r'^ifs/', include('ifs.urls')),)

ifs/models.py
# coding=utf-8
from django.db import models
from accounts.models import AbstractTimtecUser
from django.utils.translation import ugettext_lazy as _


class Campus(models.Model):
    name = models.CharField(_('Name'), max_length=30, blank=True)
    city = models.CharField(_('City'), max_length=30)
    address = models.CharField(_('Address'), max_length=30, blank=True)

    def __unicode__(self):
        return self.name or self.city


class IfUser(AbstractTimtecUser):
    # students fields
    # if_id eh o identificador de matricula
    email = models.EmailField(_('Email address'), blank=True, unique=False)

    ifid = models.CharField(_('Academic ID'), max_length=30, blank=True)
    course = models.CharField(_('Course'), max_length=30, blank=True)
    klass = models.CharField(_('Class'), max_length=30, blank=True)

    # professors fields
    cpf = models.CharField(_('Cpf'), max_length=30, blank=True)
    siape = models.CharField(_('Siape'), max_length=30, blank=True)

    # common fields
    campus = models.ForeignKey(Campus, verbose_name=_('Campus'), related_name='users', null=True, blank=True)
    is_if_staff = models.BooleanField(default=False)

ifs/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user_model
from django import forms
from django.shortcuts import redirect
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from allauth.account.forms import LoginForm


class BaseUserChangeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(BaseUserChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].required = True
        self.fields['password2'].required = True

    email = forms.RegexField(label=_("email"), max_length=75, regex=r"^[\w.@+-]+$")

    password1 = forms.CharField(widget=forms.PasswordInput, label=_("Password"), required=False)
    password2 = forms.CharField(widget=forms.PasswordInput, label=_("Password (again)"), required=False)

    accept_terms = forms.BooleanField(label=_('Accept '), initial=False, required=False)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

    def clean_accept_terms(self):
        data = self.cleaned_data.get('accept_terms')
        if settings.TERMS_ACCEPTANCE_REQUIRED and not data:
                raise forms.ValidationError(_('You must agree to the Terms of Use to use %(site_name)s.'),
                                            params={'site_name': settings.SITE_NAME},)
        return data


class SignupStudentCompletion(BaseUserChangeForm):

    def __init__(self, *args, **kwargs):
        super(SignupStudentCompletion, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['city'].required = True
        self.fields['ifid'].required = True
        self.fields['course'].required = True
        self.fields['klass'].required = True
        self.fields['campus'].required = True

    class Meta:
        model = get_user_model()
        fields = ('ifid', 'first_name', 'last_name', 'email', 'campus', 'city', 'course', 'klass')

    def save(self, **kwargs):
        user = super(SignupStudentCompletion, self).save(commit=False)
        user.ifid = self.cleaned_data['ifid']
        user.course = self.cleaned_data['course']
        user.klass = self.cleaned_data['klass']
        user.campus = self.cleaned_data['campus']
        user.city = self.cleaned_data['city']
        if self.cleaned_data['password1']:
            user.set_password(self.cleaned_data['password1'])
        user.accepted_terms = self.cleaned_data['accept_terms']
        user.save()


class SignupProfessorCompletion(BaseUserChangeForm):

    def __init__(self, *args, **kwargs):
        super(SignupProfessorCompletion, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['city'].required = True
        self.fields['siape'].required = True
        self.fields['cpf'].required = True
        self.fields['campus'].required = True

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'campus', 'city', 'siape', 'cpf')

    def save(self, **kwargs):
        user = super(SignupProfessorCompletion, self).save(commit=False)
        user.ifid = self.cleaned_data['siape']
        user.course = self.cleaned_data['cpf']
        user.campus = self.cleaned_data['campus']
        user.city = self.cleaned_data['city']
        if self.cleaned_data['password2']:
            user.set_password(self.cleaned_data['password2'])
        user.accepted_terms = self.cleaned_data['accept_terms']
        user.save()


class IfSignupForm(BaseUserChangeForm):

    def __init__(self, *args, **kwargs):
        super(IfSignupForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['city'].required = True
        # self.fields['campus'] = forms.ModelChoiceField(queryset=Campus.objects.all())

    if_student = forms.BooleanField(required=False)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'campus', 'city', 'course', 'klass')

    def clean_username(self):
        data = self.cleaned_data['username']
        if not data:
            if 'if_student' in self.data:
                raise forms.ValidationError('O campo código de matrícula é obrigatório para alunos do IFSUL.')
            else:
                super(IfSignupForm, self).clean_username(self)
        return data

    def clean_course(self):
        data = self.cleaned_data['course']
        if 'if_student' in self.data and not data:
            raise forms.ValidationError('O campo curso é obrigatório para alunos do IFSUL.')
        return data

    def clean_klass(self):
        data = self.cleaned_data['klass']
        if 'if_student' in self.data and not data:
            raise forms.ValidationError('O campo turma é obrigatório para alunos do IFSUL.')
        return data

    def clean_campus(self):
        data = self.cleaned_data['campus']
        if 'if_student' in self.data and not data:
            raise forms.ValidationError('O campo campus é obrigatório para alunos do IFSUL.')
        return data

    def signup(self, request, user):
        if 'if_student' in self.data:
            user.ifid = self.cleaned_data['username']
            user.course = self.cleaned_data['course']
            user.klass = self.cleaned_data['klass']
            user.campus = self.cleaned_data['campus']
            user.city = self.cleaned_data['city']
            user.is_if_staff = True
            user.accepted_terms = self.cleaned_data['accept_terms']
            user.save()


class IfLoginForm(LoginForm):
    def login(self, request, redirect_url=None):
        response = super(IfLoginForm, self).login(request, redirect_url)
        if self.user.is_authenticated():
            if self.user.is_if_staff:
                if request.user.groups.filter(name='professors').exists():
                    if not (self.user.campus and self.user.cpf and self.user.siape):
                        url = reverse_lazy('signup_completion')
                        url += '?next=' + response.url
                        return redirect(url)
                else:
                    if not (self.user.campus and self.user.klass and self.user.course and self.user.ifid):
                        url = reverse_lazy('signup_completion')
                        url += '?next=' + response.url
                        return redirect(url)
        return response

themes/ifs-colors/templates/ifs/signup-completion.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

<div id="signup-wrapper" class="container">
    <div class="centered" ng-app="">
        <h1>
            <i class="fa fa-smile-o"></i><br/>
            {% trans "Please verify and complete you account information" %}
        </h1>
        <form method="post" action="{% url 'signup_completion' %}" class="form-horizontal">{% csrf_token %}
            <div class="form-group">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Full Name" %}</label>

                <div class="col-sm-8 col-xs-12">
                    <div class="row">
                        {% with errors=form.first_name.errors %}
                        <div class="col-sm-6 col-xs-12{{ errors|yesno:" has-error,"}}">
                            <input name="first_name" type="text" class="form-control first-name" placeholder="Primeiro nome" value="{{form.first_name.value}}">
                            {% for error in errors %}<small>{{error}}</small>{% endfor %}
                        </div>
                        {% endwith %}

                        {% with errors=form.last_name.errors %}
                        <div class="col-sm-6 col-xs-12{{ errors|yesno:" has-error,"}}">
                            <input name="last_name" type="text" class="form-control" placeholder="Último nome" value="{{form.last_name.value}}">
                            {% for error in errors %}<small>{{error}}</small>{% endfor %}
                        </div>
                        {% endwith %}
                    </div>
                </div>
            </div>

            {% with errors=form.email.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "E-mail" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="email" type="email" value="{{form.email.value|default_if_none:""}}" class="form-control" placeholder="Your e-mail">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.password1.errors %}
            <div class="form-group{% if errors or form.non_field_errors %} has-error{% endif %}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Password" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <p><input name="password1" type="password" class="form-control" placeholder="{% trans 'Really strong password' %}"></p>
                    <input name="password2" type="password" class="form-control" placeholder="{% trans 'Password confirmation' %}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                    {% for error in form.non_field_errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.city.errors %}
            <div class="form-group{{ errors|yesno:" has-error,"}}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "City" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="city" type="text" class="form-control" placeholder="Qual cidade você vive?" value="{{form.city.value}}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.campus.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Campus" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <select id="id_campus" class="form-control" name="campus">
                        {% for x,y in form.fields.campus.choices %}
                            <option value="{{ x }}">{{ y }}</option>
                        {% endfor %}
                    </select>
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% if is_professor %}

            {% with errors=form.siape.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">Siape</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="siape" type="text" value="{{form.siape.value|default_if_none:""}}" class="form-control" placeholder="Siape">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.cpf.errors %}
            <div class="form-group{{ errors|yesno:" has-error,"}}">
                <label class="col-sm-3 col-xs-12 control-label">CPF</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="cpf" type="text" class="form-control" placeholder="Qual seu CPF?" value="{{form.cpf.value}}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% else %}

            {% with errors=form.ifid.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Academic Identifier" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="ifid" type="text" value="{{form.ifid.value|default_if_none:""}}" class="form-control" placeholder="{% trans 'Academic Identifier' %}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.course.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Course" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="course" type="text" value="{{form.course.value|default_if_none:""}}" class="form-control" placeholder="{% trans 'Course' %}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% with errors=form.klass.errors %}
            <div class="form-group{{ errors|yesno:' has-error,' }}">
                <label class="col-sm-3 col-xs-12 control-label">{% trans "Class" %}</label>
                <div class="col-sm-8 col-xs-12">
                    <input name="klass" type="text" value="{{form.klass.value|default_if_none:""}}" class="form-control" placeholder="{% trans 'Class' %}">
                    {% for error in errors %}<small>{{error}}</small>{% endfor %}
                </div>
            </div>
            {% endwith %}

            {% endif %}

            <div class="row submit textright">
                <div class="col-sm-11">
                    <button type="submit" class="btn btn-success">{% trans "Save" %}</button>
                </div>
            </div>
        </form>
</div>
{% endblock %}